config/routes.rb
Issues::Application.routes.draw do
  devise_for :users

  resources :issues do
    resources :notes, :only => :create
  end

  root :to => "issues#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all
    elsif user.role == 'moderator'
      can [:create, :read], Issue
      can :manage, Note
    elsif user.role == 'user'
      can [:create, :read], :all
      can :manage, Issue, :user_id => user.id
    else
      can :read, [Issue, Note]
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :notes
  belongs_to :user
  belongs_to :assignee, :class_name => 'User',
    :foreign_key => 'assignee_id'

  STATUS_OPTIONS = [ 'open', 'closed' ]
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :issue
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, 
    :remember_me, :username, :role, :photo

  ROLES = ['admin', 'moderator', 'user']

  has_attached_file :photo

  has_many :issues
  has_many :notes
  has_many :assigned_issues, :class_name => "Issue",
    :foreign_key => "assignee_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  authorize_resource

  # GET /issues
  # GET /issues.xml
  def index
    @search = Issue.search params[:search]
    @issues = @search.paginate :page => params[:page],
      :per_page => 5

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.xml
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.xml
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.xml
  def create
    @issue = Issue.new(params[:issue])
    @issue.user_id = current_user

    respond_to do |format|
      if @issue.save
        format.html { redirect_to(@issue, :notice => 'Issue was successfully created.') }
        format.xml  { render :xml => @issue, :status => :created, :location => @issue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.xml
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to(@issue, :notice => 'Issue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.xml
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to(issues_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @issue = Issue.find(params[:issue_id])
    @note = @issue.notes.build(params[:note])
    @note.user = current_user
    @note.save
    redirect_to issue_path(@issue)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Issue::STATUS_OPTIONS %>
  </div>
  <div class="field">
    <%= f.label :assignee_id, "Assign To" %><br />
    <%= f.collection_select :assignee_id, User.all, :id, :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br />

app/views/issues/edit.html.erb
<h2>Edit</h2>

<%= render 'form' %>

<p><%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %></p>

app/views/issues/index.html.erb
<%= form_for @search do |f| %>
  <p>
    <%= f.text_field :description_contains %>
    <%= f.submit 'Search' %>
  </p>
<% end %>

<% if can? :create, Issue %>
  <p><%= link_to 'New Issue', new_issue_path %></p>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= issue.title %></td>
    <td><%= issue.description %></td>
    <td><%= issue.status %></td>
    <td>
      <%= link_to 'Show', issue %>
      <% if can? :manage, issue %>
        | <%= link_to 'Edit', edit_issue_path(issue) %>
        | <%= link_to 'Destroy', issue, 
          :confirm => 'Are you sure?', :method => :delete %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= will_paginate @issues %>

app/views/issues/new.html.erb
<h2>New</h2>

<%= render 'form' %>

<p><%= link_to 'Back', issues_path %></p>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @issue.title %></h2>

<table>
  <tr>
    <th>Status</th><th>Author</th><th>Assigned To</th>
  </tr>
  <tr>
    <td><%= @issue.status %></td>
    <td><%= @issue.user.try :email %></td>
    <td><%= @issue.assignee.try :email %></td>
  </tr>
</table>

<p><b>Description:</b></p>

<p><%= @issue.description %></p>

<br />

<p><%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %></p>

<br />

<h2>Notes</h2>

<% @issue.notes.each do |note| %>
  <p><%= note.user.try :email %> said:</p>
  <blockquote><p><%= note.body %></p></blockquote>
<% end %>

<h3>Add A Note</h3>
<%= form_for([@issue, @issue.notes.build]) do |f| %>
  <div class="field">
    <%= f.label :body, 'Note' %><br />
    <%= f.text_area :body, :rows => 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Issues</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p>
  <% if user_signed_in? %>
    <%= link_to "Profile", edit_user_registration_path %> |
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %> |
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>
  </p>

  <h1>Issues</h1>

  <%= yield %>

</body>
</html>